export interface GeneratedOptions {
    'starting-tablet-count': number;
    'open-thunderhead': 'Ballad' | 'Open';
    'starting-sword': 'Swordless' | 'Practice Sword' | 'Goddess Sword' | 'Goddess Longsword' | 'Goddess White Sword' | 'Master Sword' | 'True Master Sword';
    'required-dungeon-count': number;
    'imp2-skip': boolean;
    'empty-unrequired-dungeons': boolean;
    'triforce-required': boolean;
    'triforce-shuffle': 'Vanilla' | 'Sky Keep' | 'Anywhere';
    'randomize-entrances': 'None' | 'Required Dungeons Separately' | 'All Surface Dungeons' | 'All Surface Dungeons + Sky Keep';
    'randomize-trials': boolean;
    'no-spoiler-log': boolean;
    'shopsanity': boolean;
    'rupoor-mode': 'Off' | 'Added' | 'Rupoor Mayhem' | 'Rupoor Insanity';
    'rupeesanity': boolean;
    'gondo-upgrades': boolean;
    'got-start': 'Lowered' | 'Raised';
    'got-sword-requirement': 'Goddess Sword' | 'Goddess Longsword' | 'Goddess White Sword' | 'Master Sword' | 'True Master Sword';
    'got-dungeon-requirement': 'Required' | 'Unrequired';
    'open-lmf': 'Nodes' | 'Main Node' | 'Open';
    'skip-horde': boolean;
    'skip-g3': boolean;
    'skip-demise': boolean;
    'map-mode': 'Removed' | 'Vanilla' | 'Own Dungeon - Restricted' | 'Own Dungeon - Unrestricted' | 'Anywhere';
    'small-key-mode': 'Vanilla' | 'Own Dungeon - Restricted' | 'Lanayru Caves Key Only' | 'Anywhere';
    'boss-key-mode': 'Vanilla' | 'Own Dungeon' | 'Anywhere';
    'logic-mode': 'BiTless' | 'No Logic';
    'enabled-tricks-bitless': string[];
    'enabled-tricks-glitched': string[];
    'song-hints': 'None' | 'Basic' | 'Advanced' | 'Direct';
    'bit-patches': 'Disable BiT' | 'Vanilla' | 'Fix BiT Crashes';
    'impa-sot-hint': boolean;
    'sword-dungeon-reward': 'None' | 'Heart Container' | 'Final Check';
    'open-et': boolean;
    'demise-count': number;
    'cube-sots': boolean;
    'precise-item': boolean;
    'shuffle-trial-objects': 'None' | 'Simple' | 'Advanced' | 'Full';
    'dowsing-after-whitesword': boolean;
    'chest-dowsing': 'Vanilla' | 'All Chests' | 'Progress Items';
    'dungeon-dowsing': boolean;
    'excluded-locations': string[];
    'open-lake-floria': 'Vanilla' | 'Talk to Yerbal' | 'Open';
    'upgraded-skyward-strike': boolean;
    'fast-air-meter': boolean;
    'enable-heart-drops': boolean;
    'damage-multiplier': number;
    'hint-distribution': 'Weak' | 'Balanced' | 'Junk' | 'Co-op S1' | 'S2 - 2D' | 'S2 - 3D' | 'S2 - 3D EUD Off' | 'CDMC' | 'Dowsing & Fi Hints' | '2D Dowsing & Fi Hints' | 'Boss Keysanity Fi Hints' | 'Strong Dowsing All Dungeons' | 'Custom';
    'starting-items': string[];
    'starting-crystal-packs': number;
    'random-starting-item': boolean;
    'starting-bottles': number;
    'start-with-hylian-shield': boolean;
    'starting-heart-containers': number;
    'starting-heart-pieces': number;
    'full-starting-wallet': boolean;
    'full-wallet-upgrades': boolean;
    'max-starting-bugs': boolean;
    'max-starting-treasures': boolean;
    'randomize-boss-key-puzzles': boolean;
    'tadtonesanity': boolean;
    'starting-tadtones': number;
    'fs-lava-flow': boolean;
    'peatrice-conversations': number;
    'random-start-entrance': 'Vanilla' | 'Bird Statues' | 'Any Surface Region' | 'Any';
    'limit-start-entrance': boolean;
    'treasuresanity-in-silent-realms': boolean;
    'trial-treasure-amount': number;
}
